#!/usr/bin/env bash

set -Eeuo pipefail

BUILD_TYPE=${BUILD_TYPE:-Debug}
DIR=".build-$BUILD_TYPE"

cmake -DCMAKE_BUILD_TYPE="$BUILD_TYPE" -S . -B "$DIR"
#cmake --build "$DIR" --target install
make -j -C "$DIR" install
