#!/usr/bin/env bash

set -Eeuo pipefail

GIT_ROOT="$(git rev-parse --show-toplevel)"

chmod +x "$GIT_ROOT/tools/git-hooks/pre-commit"
ln -rs "$GIT_ROOT/tools/git-hooks/pre-commit" "$GIT_ROOT/.git/hooks/"
